spring:
  h2:
    console:
      enabled: true

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop